<?php
return [
	[
		'name'            => 'Курьер',
		'code'            => 'courier',
		'isActive'        => 1,
		'fixedCost'       => '200',
		'info'            => '',
		'terms'           => '1 день',
		'serviceShownFor' => '2',
		'created_at'      => '1490259688',
		'updated_at'      => '1490383939',
	],
	[
		'name'            => 'Почта России',
		'code'            => 'post',
		'isActive'        => 1,
		'fixedCost'       => null,
		'info'            => null,
		'terms'           => null,
		'serviceShownFor' => '3',
		'created_at'      => '1490267046',
		'updated_at'      => '1490267046',
	],
	[
		'name'            => 'Почта России наложенным',
		'code'            => 'post_naloj',
		'isActive'        => 0,
		'fixedCost'       => null,
		'info'            => '',
		'terms'           => '',
		'serviceShownFor' => '3',
		'created_at'      => '1490267079',
		'updated_at'      => '1490381077',
	],
	[
		'name'            => 'Самовывоз',
		'code'            => 'pickup',
		'isActive'        => 1,
		'fixedCost'       => '0',
		'info'            => 'Самостоятельно забираете в офисе.',
		'terms'           => null,
		'serviceShownFor' => '1',
		'created_at'      => '1490267114',
		'updated_at'      => '1490371242',
	],
	[
		'name'            => 'СДЭК',
		'code'            => 'cdek-store',
		'isActive'        => 0,
		'fixedCost'       => null,
		'info'            => null,
		'terms'           => null,
		'serviceShownFor' => '3',
		'created_at'      => '1490267198',
		'updated_at'      => '1490267209',
	],
];